from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest

from app.compliance.normaliser import (
    ComplianceNormaliser,
    _compile_redact_rules,
    _compile_rules,
    _is_noise,
    _load_extra_lines,
    _unwrap_braces,
)

# ------------------------------------------------------------------
# Pure helper functions
# ------------------------------------------------------------------


class TestUnwrapBraces:
    def test_unwraps_singleton_brace_line(self):
        assert _unwrap_braces('configure { system name "r1" }') == 'configure system name "r1"'

    def test_leaves_normal_line_unchanged(self):
        line = "configure router bgp"
        assert _unwrap_braces(line) == line

    def test_leaves_multiword_configure_without_braces_unchanged(self):
        line = "configure system security ssh"
        assert _unwrap_braces(line) == line

    def test_handles_inner_content_with_spaces(self):
        result = _unwrap_braces("configure { router isis 0 level-capability level-2 }")
        assert result == "configure router isis 0 level-capability level-2"


class TestIsNoise:
    def test_comment_line_is_noise(self):
        assert _is_noise("# Generated by SR OS") is True

    def test_regular_line_is_not_noise(self):
        assert _is_noise("configure system name r1") is False

    def test_empty_string_is_not_noise(self):
        assert _is_noise("") is False

    def test_line_with_hash_not_at_start_is_not_noise(self):
        assert _is_noise('configure system security keychains key "abc#123"') is False


class TestCompileRules:
    def test_exact_match(self):
        rules = _compile_rules(
            [{"match": "exact", "value": 'configure qos vlan-qos-policy "default"'}]
        )
        assert rules[0]('configure qos vlan-qos-policy "default"') is True
        assert rules[0]("configure qos vlan-qos-policy other") is False

    def test_startswith_match(self):
        rules = _compile_rules([{"match": "startswith", "value": "configure log filter"}])
        assert rules[0]("configure log filter 1001 entry 10") is True
        assert rules[0]("configure router bgp") is False

    def test_regex_match(self):
        rules = _compile_rules([{"match": "regex", "value": r"^configure port \d+/\d+/c\d+$"}])
        assert rules[0]("configure port 1/1/c1") is True
        assert rules[0]("configure port 1/1/c1 admin-state enable") is False

    def test_unknown_match_type_raises(self):
        with pytest.raises(ValueError, match="Unknown ignore rule match type"):
            _compile_rules([{"match": "contains", "value": "foo"}])

    def test_lambda_closure_captures_correct_value(self):
        rules = _compile_rules(
            [
                {"match": "exact", "value": "line-a"},
                {"match": "exact", "value": "line-b"},
            ]
        )
        assert rules[0]("line-a") is True
        assert rules[0]("line-b") is False
        assert rules[1]("line-b") is True
        assert rules[1]("line-a") is False

    def test_empty_rules_list_returns_empty(self):
        assert _compile_rules([]) == []


class TestCompileRedactRules:
    def test_redacts_matching_line(self):
        rules = _compile_redact_rules(
            [
                {
                    "match": "regex",
                    "value": r"^(configure system security user-params .* password) .*$",
                    "replace": r"\1 <redacted>",
                }
            ]
        )
        result = rules[0](
            "configure system security user-params local-user user admin password secret123"
        )
        assert (
            result
            == "configure system security user-params local-user user admin password <redacted>"
        )

    def test_non_matching_line_is_unchanged(self):
        rules = _compile_redact_rules(
            [
                {
                    "match": "regex",
                    "value": r"^(configure .* password) .*$",
                    "replace": r"\1 <redacted>",
                }
            ]
        )
        line = "configure router bgp neighbor 10.0.0.1"
        assert rules[0](line) == line

    def test_missing_replace_key_raises(self):
        with pytest.raises(ValueError, match="missing 'replace' key"):
            _compile_redact_rules([{"match": "regex", "value": r"^foo.*$"}])

    def test_empty_rules_list_returns_empty(self):
        assert _compile_redact_rules([]) == []


# ------------------------------------------------------------------
# _load_extra_lines
# ------------------------------------------------------------------


class TestLoadExtraLines:
    def test_returns_empty_when_no_files_exist(self, tmp_path, monkeypatch):
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        result = _load_extra_lines(role_name="core", hostname="r1")
        assert result == frozenset()

    def test_loads_role_file(self, tmp_path, monkeypatch):
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        (tmp_path / "core.cfg").write_text("configure router bgp\n/configure system name r1\n")
        result = _load_extra_lines(role_name="core", hostname="r1-unique")
        assert "configure router bgp" in result
        assert "configure system name r1" in result

    def test_loads_hostname_file(self, tmp_path, monkeypatch):
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        (tmp_path / "r1.cfg").write_text("configure router isis 0\n")
        result = _load_extra_lines(role_name="core", hostname="r1")
        assert "configure router isis 0" in result

    def test_unions_role_and_hostname_files(self, tmp_path, monkeypatch):
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        (tmp_path / "pe.cfg").write_text("shared-line\n")
        (tmp_path / "pe1.cfg").write_text("device-specific-line\n")
        result = _load_extra_lines(role_name="pe", hostname="pe1")
        assert "shared-line" in result
        assert "device-specific-line" in result

    def test_loads_base_file_for_any_device(self, tmp_path, monkeypatch):
        # base.cfg applies globally, regardless of role or hostname — the estate-wide
        # layer mirroring ignore/base.yaml.
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        (tmp_path / "base.cfg").write_text('configure system security ... user "admin"\n')
        result = _load_extra_lines(role_name="any-role", hostname="any-host")
        assert 'configure system security ... user "admin"' in result

    def test_unions_base_role_and_hostname_files(self, tmp_path, monkeypatch):
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        (tmp_path / "base.cfg").write_text("global-line\n")
        (tmp_path / "pe.cfg").write_text("role-line\n")
        (tmp_path / "pe1.cfg").write_text("host-line\n")
        result = _load_extra_lines(role_name="pe", hostname="pe1")
        assert {"global-line", "role-line", "host-line"} <= result

    def test_strips_leading_slash(self, tmp_path, monkeypatch):
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        (tmp_path / "core.cfg").write_text("/configure router bgp\n")
        result = _load_extra_lines(role_name="core", hostname="r-unique")
        assert "configure router bgp" in result

    def test_skips_comment_and_blank_lines(self, tmp_path, monkeypatch):
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        (tmp_path / "core.cfg").write_text("# comment\n\nconfigure router bgp\n")
        result = _load_extra_lines(role_name="core", hostname="r-unique")
        assert "# comment" not in result
        assert "" not in result
        assert "configure router bgp" in result

    def test_drops_bare_slash_line(self, tmp_path, monkeypatch):
        # A stray "/" in an extra .cfg becomes "" after the leading-slash strip
        # and must NOT be injected — symmetrical to the normalise() guard.
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", tmp_path)
        (tmp_path / "core.cfg").write_text("/\nconfigure router bgp\n")
        result = _load_extra_lines(role_name="core", hostname="r-unique")
        assert "" not in result
        assert "configure router bgp" in result


# ------------------------------------------------------------------
# ComplianceNormaliser fixtures
# ------------------------------------------------------------------


@pytest.fixture
def ignore_dir(tmp_path):
    d = tmp_path / "ignore"
    d.mkdir()
    (d / "base.yaml").write_text("ignore: []\nredact: []\n")
    return d


@pytest.fixture
def extra_dir(tmp_path):
    d = tmp_path / "extra"
    d.mkdir()
    return d


@pytest.fixture
def normaliser(session, ignore_dir, extra_dir, monkeypatch):
    monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
    monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
    monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
    with (
        patch("app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"),
        patch("app.compliance.normaliser.get_device_role_by_hostname", return_value="core"),
    ):
        yield ComplianceNormaliser(session=session)


# ------------------------------------------------------------------
# ComplianceNormaliser.normalise — format transforms
# ------------------------------------------------------------------


class TestNormaliseFormatTransforms:
    def test_strips_leading_whitespace(self, normaliser):
        result = normaliser.normalise(hostname="r1", raw="    configure router bgp\n")
        assert "configure router bgp" in result.lines

    def test_drops_empty_lines(self, normaliser):
        result = normaliser.normalise(hostname="r1", raw="\n\nconfigure router bgp\n\n")
        assert "" not in result.lines
        assert len(result.lines) == 1

    def test_drops_noise_comment_lines(self, normaliser):
        result = normaliser.normalise(
            hostname="r1", raw="# Generated by SR OS\nconfigure router bgp\n"
        )
        assert not any(line.startswith("#") for line in result.lines)
        assert "configure router bgp" in result.lines

    def test_strips_leading_slash(self, normaliser):
        result = normaliser.normalise(hostname="r1", raw="/configure router bgp\n")
        assert "configure router bgp" in result.lines
        assert "/configure router bgp" not in result.lines

    def test_unwraps_brace_singleton(self, normaliser):
        result = normaliser.normalise(hostname="r1", raw='configure { system name "r1" }\n')
        assert 'configure system name "r1"' in result.lines

    def test_result_hostname_matches_input(self, normaliser):
        result = normaliser.normalise(hostname="core1.tst-001", raw="configure router bgp\n")
        assert result.hostname == "core1.tst-001"

    def test_deduplicates_identical_lines(self, normaliser):
        result = normaliser.normalise(
            hostname="r1",
            raw="configure router bgp\nconfigure router bgp\n",
        )
        assert len(result.lines) == 1

    def test_drops_bare_slash_line(self, normaliser):
        # A stray "/" emitted by a template becomes "" after the leading-slash
        # strip and must NOT be injected into the rendered set (it would surface
        # as a phantom diff entry on every device that hits the bug).
        result = normaliser.normalise(
            hostname="r1",
            raw="/\nconfigure router bgp\n",
        )
        assert "" not in result.lines
        assert "configure router bgp" in result.lines

    def test_drops_brace_only_line_that_unwraps_to_empty(self, normaliser):
        # Defense in depth: any line that becomes empty after the format
        # transforms (slash-strip + brace-unwrap) is dropped, not added.
        result = normaliser.normalise(hostname="r1", raw="/\n")
        assert result.lines == frozenset()


# ------------------------------------------------------------------
# ComplianceNormaliser.normalise — ignore rules
# ------------------------------------------------------------------


class TestNormaliseIgnoreRules:
    def test_exact_rule_drops_matching_line(self, session, ignore_dir, extra_dir, monkeypatch):
        (ignore_dir / "base.yaml").write_text(
            'ignore:\n  - match: exact\n    value: "configure qos vlan-qos-policy \\"default\\""\n'
        )
        monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
        monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
        with (
            patch(
                "app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"
            ),
            patch("app.compliance.normaliser.get_device_role_by_hostname", return_value="core"),
        ):
            n = ComplianceNormaliser(session=session)
            result = n.normalise(
                hostname="r1",
                raw='configure qos vlan-qos-policy "default"\nconfigure router bgp\n',
            )
        assert 'configure qos vlan-qos-policy "default"' not in result.lines
        assert "configure router bgp" in result.lines

    def test_startswith_rule_drops_subtree(self, session, ignore_dir, extra_dir, monkeypatch):
        (ignore_dir / "base.yaml").write_text(
            'ignore:\n  - match: startswith\n    value: "configure log filter"\n'
        )
        monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
        monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
        with (
            patch(
                "app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"
            ),
            patch("app.compliance.normaliser.get_device_role_by_hostname", return_value="core"),
        ):
            n = ComplianceNormaliser(session=session)
            result = n.normalise(
                hostname="r1",
                raw="configure log filter 1001 entry 10 action drop\nconfigure router bgp\n",
            )
        assert "configure log filter 1001 entry 10 action drop" not in result.lines
        assert result.ignored_count == 1

    def test_ignored_count_is_accurate(self, session, ignore_dir, extra_dir, monkeypatch):
        (ignore_dir / "base.yaml").write_text(
            'ignore:\n  - match: startswith\n    value: "configure log"\n'
        )
        monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
        monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
        with (
            patch(
                "app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"
            ),
            patch("app.compliance.normaliser.get_device_role_by_hostname", return_value="core"),
        ):
            n = ComplianceNormaliser(session=session)
            result = n.normalise(
                hostname="r1",
                raw="configure log filter 1001\nconfigure log log-id 99\nconfigure router bgp\n",
            )
        assert result.ignored_count == 2


# ------------------------------------------------------------------
# ComplianceNormaliser.normalise — redact rules
# ------------------------------------------------------------------


class TestNormaliseRedactRules:
    def test_redact_replaces_secret_value(self, session, ignore_dir, extra_dir, monkeypatch):
        (ignore_dir / "base.yaml").write_text(
            "ignore: []\n"
            "redact:\n"
            "  - match: regex\n"
            '    value: "^(configure system security user-params .* password) .*$"\n'
            '    replace: "\\\\1 <redacted>"\n'
        )
        monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
        monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
        with (
            patch(
                "app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"
            ),
            patch("app.compliance.normaliser.get_device_role_by_hostname", return_value="core"),
        ):
            n = ComplianceNormaliser(session=session)
            result = n.normalise(
                hostname="r1",
                raw="configure system security user-params local-user user admin password secret123\n",
            )
        assert any("<redacted>" in line for line in result.lines)
        assert not any("secret123" in line for line in result.lines)


# ------------------------------------------------------------------
# ComplianceNormaliser.normalise_rendered — extra lines
# ------------------------------------------------------------------


class TestNormaliseRendered:
    def test_extra_lines_are_injected(self, session, ignore_dir, extra_dir, monkeypatch):
        (extra_dir / "core.cfg").write_text("configure router isis 0\n")
        monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
        monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
        with (
            patch(
                "app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"
            ),
            patch("app.compliance.normaliser.get_device_role_by_hostname", return_value="core"),
        ):
            n = ComplianceNormaliser(session=session)
            result = n.normalise_rendered(hostname="r1", raw="configure router bgp\n")
        assert "configure router isis 0" in result.lines
        assert "configure router bgp" in result.lines
        assert result.extra_count == 1

    def test_extra_count_zero_when_no_extra_file(self, normaliser):
        result = normaliser.normalise_rendered(hostname="r1", raw="configure router bgp\n")
        assert result.extra_count == 0

    def test_normalise_rendered_without_extra_equals_normalise(self, normaliser):
        raw = "configure router bgp\nconfigure system name r1\n"
        plain = normaliser.normalise(hostname="r1", raw=raw)
        rendered = normaliser.normalise_rendered(hostname="r1", raw=raw)
        assert plain.lines == rendered.lines

    def test_ignore_rule_suppresses_extra_injected_line(
        self, session, ignore_dir, extra_dir, monkeypatch
    ):
        # Bug fix: an ignore rule must apply to extra-injected lines just like
        # it does to rendered lines. Previously extras bypassed the ignore
        # path, leaving per-host ignore entries silently ineffective.
        (ignore_dir / "base.yaml").write_text(
            'ignore:\n  - match: startswith\n    value: "configure mirror"\n'
        )
        (extra_dir / "core.cfg").write_text(
            'configure mirror mirror-dest "999" admin-state enable\nconfigure router isis 0\n'
        )
        monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
        monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
        with (
            patch(
                "app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"
            ),
            patch("app.compliance.normaliser.get_device_role_by_hostname", return_value="core"),
        ):
            n = ComplianceNormaliser(session=session)
            result = n.normalise_rendered(hostname="r1", raw="configure router bgp\n")
        assert 'configure mirror mirror-dest "999" admin-state enable' not in result.lines
        assert "configure router isis 0" in result.lines
        assert "configure router bgp" in result.lines
        assert result.extra_count == 1
        assert result.ignored_count == 1

    def test_non_matching_extra_lines_pass_through(
        self, session, ignore_dir, extra_dir, monkeypatch
    ):
        (ignore_dir / "base.yaml").write_text(
            'ignore:\n  - match: startswith\n    value: "configure mirror"\n'
        )
        (extra_dir / "core.cfg").write_text("configure router isis 0\nconfigure router bgp\n")
        monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
        monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
        with (
            patch(
                "app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"
            ),
            patch("app.compliance.normaliser.get_device_role_by_hostname", return_value="core"),
        ):
            n = ComplianceNormaliser(session=session)
            result = n.normalise_rendered(hostname="r1", raw="configure system name r1\n")
        assert "configure router isis 0" in result.lines
        assert "configure router bgp" in result.lines
        assert result.extra_count == 2
        assert result.ignored_count == 0

    def test_raises_when_role_not_found(self, session, ignore_dir, extra_dir, monkeypatch):
        monkeypatch.setattr("app.compliance.normaliser.IGNORE_DIR", ignore_dir)
        monkeypatch.setattr("app.compliance.normaliser.BASE_IGNORE_FILE", ignore_dir / "base.yaml")
        monkeypatch.setattr("app.compliance.normaliser.EXTRA_DIR", extra_dir)
        with (
            patch(
                "app.compliance.normaliser.get_device_model_by_hostname", return_value="7750-SR7"
            ),
            patch("app.compliance.normaliser.get_device_role_by_hostname", return_value=None),
        ):
            n = ComplianceNormaliser(session=session)
            with pytest.raises(RuntimeError, match="No role found"):
                n.normalise_rendered(hostname="unknown", raw="configure router bgp\n")


# ------------------------------------------------------------------
# Rule caching
# ------------------------------------------------------------------


class TestRuleCaching:
    def test_rules_are_cached_per_hostname(self, normaliser):
        normaliser.normalise(hostname="r1", raw="configure router bgp\n")
        normaliser.normalise(hostname="r1", raw="configure router isis\n")
        assert "r1" in normaliser._rule_cache
        assert len(normaliser._rule_cache) == 1

    def test_different_hostnames_cached_separately(self, normaliser):
        normaliser.normalise(hostname="r1", raw="configure router bgp\n")
        normaliser.normalise(hostname="r2", raw="configure router bgp\n")
        assert "r1" in normaliser._rule_cache
        assert "r2" in normaliser._rule_cache
